name: Auth - STG CD

on:
  push:
    branches:
      - master
    paths:
      - 'packages/e2e/**'
      - 'packages/shared/**'
      - 'packages/ui/**'
      - 'packages/projects/vivareal/**'

  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      ENVIRONMENT: STG AUTH
      BUILD_ENV: STG
      PROJECT: AUTH
    secrets: inherit

  deploy:
    needs: [build]
    uses: ./.github/workflows/deploy.yml
    with:
      ENVIRONMENT: STG AUTH
      BUILD_ENV: STG
    secrets: inherit

