name: Manager - STG CD

on:
  push:
    branches:
      - master
    paths:
      - 'packages/e2e/**'
      - 'packages/shared/**'
      - 'packages/projects/manager/**'

  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      ENVIRONMENT: STG MANAGER
      BUILD_ENV: STG
      PROJECT: MANAGER
      COMMAND: build-manager
    secrets: inherit

  deploy:
    needs: [build]
    uses: ./.github/workflows/deploy.yml
    with:
      ENVIRONMENT: STG MANAGER
      BUILD_ENV: STG
      PROJECT: MANAGER
      HOSTING: stg-manager
    secrets: inherit

