name: SSO - STG CI

on:
  pull_request:
    branches:
      - '*'
    paths:
      - 'packages/e2e/**'
      - 'packages/shared/**'
      - 'packages/projects/sso/**'

  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      ENVIRONMENT: STG AUTH
      BUILD_ENV: STG
      PROJECT: AUTH
    secrets: inherit

  unit-tests:
    needs: [build]
    uses: ./.github/workflows/unit-tests.yml
    with:
      ENVIRONMENT: STG AUTH
      BUILD_ENV: STG
      PROJECT: AUTH
    secrets: inherit